using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

using Demo.DecoratedHandlers.Abstractions;

// <auto-generated
namespace FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler;

using InterfaceAlias = IRequestHandler<
    global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Alpha,
    global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Omega>;

using DelegateAlias = RequestHandlerDelegate<
    global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Omega>;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class BarHandlerPipeline(IServiceProvider provider) : InterfaceAlias
{
    public Task<global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Omega> HandleAsync(
        global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Alpha input,
        CancellationToken ct = default)
    {
        var handler = provider.GetRequiredService<
            global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.BarHandler>(); 

        DelegateAlias original = () => handler.HandleAsync(input, ct);

        var b0 = provider.GetRequiredService<
            global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.LogBehavior<
                global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Alpha,
                global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Omega>>();

        DelegateAlias f0 = () => b0.HandleAsync(input, original, ct);

        return f0();
    }
}