using System;
using Microsoft.Extensions.DependencyInjection;
using Demo.DecoratedHandlers.Abstractions;

// <auto-generated
namespace Tests.PartialHandler;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineContext : IPipelineContext
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Alpha,
                global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.Omega>,
            global::Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.BarHandler,
            global::FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.PartialHandler.BarHandlerPipeline>();
    }
}
