using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Demo.DecoratedHandlers.Abstractions;

// <auto-generated
namespace FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior;

using InterfaceAlias = IRequestHandler<
    global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.Alpha,
    global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.Omega>;

using DelegateAlias = RequestHandlerDelegate<
    global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.Omega>;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class BarHandlerPipeline(IServiceProvider provider) : InterfaceAlias
{
    public Task<global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.Omega> HandleAsync(
        global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.Alpha input,
        CancellationToken ct = default)
    {
        var handler = provider.GetRequiredService<
            global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.BarHandler>(); 

        DelegateAlias original = () => handler.HandleAsync(input, ct);

        var b0 = provider.GetRequiredService<
            global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.LogBehavior<
                global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.Alpha,
                global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.Omega>>();

        DelegateAlias f0 = () => b0.HandleAsync(input, original, ct);

        return f0();
    }
}

internal static class ServiceCollectionExtensions_BarHandlerPipeline
{
    [RegisterThis]
    internal static void ReplaceHandlerWithPipeline(
        this IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            InterfaceAlias,
            global::Demo.DecoratedHandlers.Tests.Snapshots.OneBehavior.BarHandler,
            BarHandlerPipeline>();
    }
}