using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.DecoratedHandlers.Abstractions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Demo.DecoratedHandlers.Gen;

// <auto-generated
namespace MyNamespace
{ 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "1.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]
    
    public class BarPipeline(IServiceProvider provider) : IRequestHandler<Alpha, Omega>
    { 
        public Task<Omega> HandleAsync(Alpha input, CancellationToken ct = default) 
        {
            var handler = provider.GetRequiredService<Bar>(); 
            RequestHandlerDelegate<Omega> original = () => handler.HandleAsync(input, ct);

            return original();
        }
    } 

    internal static class ServiceCollectionExtensions_BarPipeline
    {
        [RegisterThis]
        internal static void ReplaceHandlerWithPipeline(this IServiceCollection services)
        {
            services.ReplaceWithPipeline<IRequestHandler<Alpha, Omega>, Bar, BarPipeline>();
        }
    }
}