using System;
using Microsoft.Extensions.DependencyInjection;
using Demo.DecoratedHandlers.Abstractions;
using Demo.DecoratedHandlers.Gen;

// <auto-generated
namespace Tests.PartialBehavior;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineRegistry : IPipelineRegistry
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Demo.DecoratedHandlers.Tests.Snapshots.PartialBehavior.Alpha,
                global::Demo.DecoratedHandlers.Tests.Snapshots.PartialBehavior.Omega>,
            global::Demo.DecoratedHandlers.Tests.Snapshots.PartialBehavior.BarHandler,
            global::FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.PartialBehavior.BarHandlerPipeline>();
    }
}
