using System;
using Microsoft.Extensions.DependencyInjection;
using Demo.DecoratedHandlers.Abstractions;

// <auto-generated
namespace Tests.TwoBehaviors;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineContext : IPipelineContext
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Demo.DecoratedHandlers.Tests.Snapshots.TwoBehaviors.Alpha,
                global::Demo.DecoratedHandlers.Tests.Snapshots.TwoBehaviors.Omega>,
            global::Demo.DecoratedHandlers.Tests.Snapshots.TwoBehaviors.BarHandler,
            global::FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.TwoBehaviors.BarHandlerPipeline>();
    }
}
