using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.DecoratedHandlers.Abstractions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Demo.DecoratedHandlers.Gen;

// <auto-generated
namespace Demo.DecoratedHandlers.Tests.Snapshots.TwoBehaviors
{ 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]
    
    public class BarHandlerPipeline(IServiceProvider provider) : IRequestHandler<Alpha, Omega>
    { 
        public Task<Omega> HandleAsync(Alpha input, CancellationToken ct = default) 
        {
            var handler = provider.GetRequiredService<BarHandler>(); 
            RequestHandlerDelegate<Omega> original = () => handler.HandleAsync(input, ct);

            var b0 = provider.GetRequiredService<LogBehavior<Alpha, Omega>>();
            RequestHandlerDelegate<Omega> f0 = () => b0.Handle(input, original, ct);
            var b1 = provider.GetRequiredService<ExceptionBehavior<Alpha, Omega>>();
            RequestHandlerDelegate<Omega> f1 = () => b1.Handle(input, f0, ct);
            return f1();
        }
    } 

    internal static class ServiceCollectionExtensions_BarHandlerPipeline
    {
        [RegisterThis]
        internal static void ReplaceHandlerWithPipeline(this IServiceCollection services)
        {
            services.ReplaceWithPipeline<IRequestHandler<Alpha, Omega>, BarHandler, BarHandlerPipeline>();
        }
    }
}