using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

using Demo.DecoratedHandlers.Abstractions;

// <auto-generated
namespace FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.SameName.HandlerNamespace;

using InterfaceAlias = IRequestHandler<
    global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.RequestNamespace.Foo,
    global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.ResponseNamespace.Foo>;

using DelegateAlias = RequestHandlerDelegate<
    global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.ResponseNamespace.Foo>;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class FooPipeline(IServiceProvider provider) : InterfaceAlias
{
    public Task<global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.ResponseNamespace.Foo> HandleAsync(
        global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.RequestNamespace.Foo input,
        CancellationToken ct = default)
    {
        var handler = provider.GetRequiredService<
            global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.HandlerNamespace.Foo>(); 

        DelegateAlias original = () => handler.HandleAsync(input, ct);

        var b0 = provider.GetRequiredService<
            global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.BehaviorNamespace.Foo<
                global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.RequestNamespace.Foo,
                global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.ResponseNamespace.Foo>>();

        DelegateAlias f0 = () => b0.HandleAsync(input, original, ct);

        return f0();
    }
}

internal static class ServiceCollectionExtensions_FooPipeline
{
    [RegisterThis]
    internal static void ReplaceHandlerWithPipeline(
        this IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            InterfaceAlias,
            global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.HandlerNamespace.Foo,
            FooPipeline>();
    }
}