using System;
using Microsoft.Extensions.DependencyInjection;
using Demo.DecoratedHandlers.Abstractions;

// <auto-generated
namespace Tests.SameName;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineContext : IPipelineContext
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.RequestNamespace.Foo,
                global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.ResponseNamespace.Foo>,
            global::Demo.DecoratedHandlers.Tests.Snapshots.SameName.HandlerNamespace.Foo,
            global::FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.SameName.HandlerNamespace.FooPipeline>();
    }
}
