using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.DecoratedHandlers.Abstractions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Demo.DecoratedHandlers.Gen;

// <auto-generated
namespace Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler
{ 
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]
    
    public class BarHandlerPipeline_1(IServiceProvider provider) : IRequestHandler<Beta, Omega>
    { 
        public Task<Omega> HandleAsync(Beta input, CancellationToken ct = default) 
        {
            var handler = provider.GetRequiredService<BarHandler>(); 
            RequestHandlerDelegate<Omega> original = () => handler.HandleAsync(input, ct);

            var b0 = provider.GetRequiredService<LogBehavior<Beta, Omega>>();
            RequestHandlerDelegate<Omega> f0 = () => b0.Handle(input, original, ct);
            return f0();
        }
    } 

    internal static class ServiceCollectionExtensions_BarHandlerPipeline_1
    {
        [RegisterThis]
        internal static void ReplaceHandlerWithPipeline(this IServiceCollection services)
        {
            services.ReplaceWithPipeline<IRequestHandler<Beta, Omega>, BarHandler, BarHandlerPipeline_1>();
        }
    }
}