using System;
using Microsoft.Extensions.DependencyInjection;
using Demo.DecoratedHandlers.Abstractions;
using Demo.DecoratedHandlers.Gen;

// <auto-generated
namespace Tests.CompositeHandler;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Demo.DecoratedHandlers.Gen", "%VERSION%")]
[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Always)]

public class PipelineRegistry : IPipelineRegistry
{
    public void Apply(IServiceCollection services)
    {
        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.Alpha,
                global::Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.Omega>,
            global::Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.BarHandler,
            global::FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.BarHandlerPipeline>();

        services.ReplaceWithPipeline<
            IRequestHandler<
                global::Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.Beta,
                global::Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.Omega>,
            global::Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.BarHandler,
            global::FancyGlobalPrefix.Demo.DecoratedHandlers.Tests.Snapshots.CompositeHandler.BarHandlerPipeline_1>();
    }
}
